name: FCIPVP
author: HappyHappyBoy
version: 1.3
Depends: [EffectLib]

main: de.teamfci.fcipvp.FCIPVP
commands:
  fcipvp:
    description: Main Command Off FCIPVP
  par:
    description: Main Command Off FCIPVP